export const attractionsMock = [
  {
    id: 1,
    title: "Озеро Тургояк",
    type: "Озеро",
    distance: 117,
    days: 1,
    rating: 4.8,
    image: "/cat1.jpg",
    description: "Одно из самых чистых озёр России.",
    position: [55.1545, 60.1406],
  },
  {
    id: 2,
    title: "Зюраткуль",
    type: "Гора",
    distance: 150,
    days: 2,
    rating: 4.9,
    image: "/cat2.jpg",
    description: "Высокогорное озеро среди хребтов.",
    position: [54.82, 59.186],
  },
  {
    id: 3,
    title: "Таганай",
    type: "История",
    distance: 100,
    days: 2,
    rating: 4.7,
    image: "/cat3.jpg",
    description: "Известный горный массив.",
    position: [55.255, 59.802],
  },
  {
    id: 4,
    title: "Кавказские водопады",
    type: "Природа",
    distance: 350,
    days: 3,
    rating: 4.6,
    image: "/cat4.jpg",
    description: "Живописные водопады среди скал.",
    position: [45.1, 41.0],
  },
  {
    id: 5,
    title: "Пещера Игнатьевская",
    type: "Пещера",
    distance: 50,
    days: 1,
    rating: 4.3,
    image: "/cat5.jpg",
    description: "Одна из красивейших пещер Урала.",
    position: [55.15, 58.30],
  },
  {
    id: 6,
    title: "Сугомакская пещера",
    type: "Пещера",
    distance: 140,
    days: 1,
    rating: 4.6,
    image: "/cat6.jpg",
    description: "Единственная мраморная пещера Урала.",
    position: [55.0, 60.0],
  },
  {
    id: 7,
    title: "Плато Устюрт",
    type: "Пустыня",
    distance: 800,
    days: 4,
    rating: 4.2,
    image: "/cat7.jpg",
    description: "Необычный ландшафт с каньонами.",
    position: [44.0, 56.0],
  },
  {
    id: 8,
    title: "Гора Иремель",
    type: "Гора",
    distance: 180,
    days: 2,
    rating: 4.9,
    image: "/cat8.jpg",
    description: "Популярный маршрут с мягким подъёмом.",
    position: [54.53, 58.80],
  },
  {
    id: 9,
    title: "Аркаим",
    type: "История",
    distance: 450,
    days: 2,
    rating: 4.7,
    image: "/cat9.jpg",
    description: "Древний город, место силы.",
    position: [52.64, 60.05],
  },
];
